project_id = "ybzhlsalbnxwkfszkloa"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.iniciar-trial]
verify_jwt = false

[functions.get-checkout-session]
verify_jwt = false

[functions.complete-onboarding]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.webhook-entrada]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.waha-proxy]
verify_jwt = false

[functions.waha-webhook]
verify_jwt = false

[functions.sync-emails]
verify_jwt = false

[functions.translate-email]
verify_jwt = false

[functions.delete-email]
verify_jwt = false

[functions.api4com-proxy]
verify_jwt = false

[functions.email-tracking]
verify_jwt = false

[functions.processar-submissao-formulario]
verify_jwt = false

[functions.processar-sla]
verify_jwt = false

[functions.processar-eventos-automacao]
verify_jwt = false
